CREATE TABLE  `customers_entry` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`email` VARCHAR( 100 ) NOT NULL ,
`mobile` VARCHAR( 100 ) NOT NULL ,
`Gender` VARCHAR( 100 ) NOT NULL ,
`Civil Status` VARCHAR( 100 ) NOT NULL  ,
`Nationality` VARCHAR( 100 ) NOT NULL
) ENGINE = INNODB;
